schema_version: 1

context:
  name: tiny-cuda-nn
  version: "2.0"
  build_number: 0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  - url: https://github.com/NVlabs/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: fea09c396f841de490944b02285946d77e43f4975ff247f2301113161d119bcd
    patches:
      - patches/0001-Use-packaging-version.patch
  - url: https://github.com/fmtlib/fmt/archive/b0c8263cb26ea178d3a5df1b984e1a61ef578950.tar.gz
    sha256: 49473ea73d3d97724fb9c69beaa7ef4547c05e53b1d9d40c8994c1e369e49faa
    target_directory: dependencies/fmt
  - url: https://github.com/NVIDIA/cutlass/archive/1eb6355182a5124639ce9d3ff165732a94ed9a70.tar.gz
    sha256: 6ea7f41ed6548b980c96459855088f10efaf3c9ef6cb3668cc094a337cef86a3
    target_directory: dependencies/cutlass
  - url: https://github.com/vector-of-bool/cmrc/archive/952ffddba731fc110bd50409e8d2b8a06abbd237.tar.gz
    sha256: 9a1e00d18da46d9765ba5a59f7275dea8b87b242b8885588b3a4694bd4d19747
    target_directory: dependencies/cmrc

build:
  number: ${{ build_number }}
  skip:
    - osx
    - win
    - cuda_compiler_version == "None"
    - cuda_compiler_version == "11.8"
  script:
    file: build.sh
  dynamic_linking:
    # tiny-cuda-nn loads the system CUDA driver library at runtime.
    missing_dso_allowlist:
      - $RPATH/libcuda.so.1

requirements:
  build:
    - ${{ compiler("cxx") }}
    - if: cuda_compiler_version != "None"
      then: ${{ compiler("cuda") }}
    - ${{ stdlib("c") }}
    - cmake
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - packaging
        - pip
        - pybind11
        - python
        - "pytorch 2.10.* *cuda*"
        - setuptools
  host:
    - pip
    - packaging
    - python
    - "pytorch 2.10.* *cuda*"
    - setuptools
    - if: cuda_compiler_version != "None"
      then:
        - cuda-version ==${{ cuda_compiler_version }}
        - cuda-cudart-dev
        - libcublas-dev
        - libcusolver-dev
        - libcusparse-dev
  run:
    - if: cuda_compiler_version != "None"
      then: cuda-cudart
    - python
    - "pytorch 2.10.* *cuda*"
  ignore_run_exports:
    from_package:
      - libcublas-dev
      - libcusolver-dev
      - libcusparse-dev

tests:
  # Importing tinycudann raises when torch.cuda.is_available() is false.
  - requirements:
      run:
        - pip
        - python
    script:
      - python -m pip check
      - python -c "import importlib.metadata as m; assert m.version('tinycudann')"

about:
  homepage: https://github.com/NVlabs/tiny-cuda-nn
  summary: Lightning fast C++/CUDA neural network framework
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - jeongseok-meta
