azure:
  free_disk_space: true
  settings_win:
    vmImage: windows-2019
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
