azure:
  free_disk_space: true
  settings_win:
    vmImage: windows-2019
  variables:
    CONDA_BLD_PATH: C:\\bld\\
    MINIFORGE_HOME: C:\Miniforge
    UPLOAD_TEMP: C:\\tmp
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
bot:
  automerge: true
